//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Information
    {
        public string Order_Number { get; set; }
        public string Product { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
