//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PosudaDBEntities : DbContext
    {
        public PosudaDBEntities()
            : base("name=PosudaDBEntities")
        {
        }

        public static PosudaDBEntities _PosudaDBEntities;

        public static PosudaDBEntities GetContext()
        {
            if (_PosudaDBEntities == null)
            {
                _PosudaDBEntities = new PosudaDBEntities();
            }
            return _PosudaDBEntities;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee_role> Employee_role { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Points_Issuance> Points_Issuance { get; set; }
        public virtual DbSet<Product_Categories> Product_Categories { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Order_Information> Order_Information { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
    }
}
