//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public Nullable<int> Product_category { get; set; }
        public int Current_discount { get; set; }
        public Nullable<int> Quantity_in_stock { get; set; }
        public string Description { get; set; }
        public string Product_code { get; set; }
        public byte[] Product_Image { get; set; }
    
        public virtual Product_Categories Product_Categories { get; set; }
    }
}
